# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

install! 'cocoapods', :disable_input_output_paths => true

target 'DemoTestPodFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoTestPodFramework
  pod 'TestPodFramework', :path => '../'
end

target 'TestPodFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestPodFramework
  pod 'Alamofire', '~> 5.4.4'
  
  target 'TestPodFrameworkTests' do
    # Pods for testing
  end

end
